"""empty message

Revision ID: 179d84ad6b6f
Revises: 401b3450a6d2
Create Date: 2023-12-25 13:42:37.989854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179d84ad6b6f'
down_revision = '401b3450a6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
