"""empty message

Revision ID: e050cdc2672e
Revises: 179d84ad6b6f
Create Date: 2023-12-27 14:13:43.481059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e050cdc2672e'
down_revision = '179d84ad6b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doors', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('luggage', sa.Integer(), nullable=True))
        batch_op.drop_column('year')
        batch_op.drop_column('license_plate')
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('license_plate', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=True))
        batch_op.drop_column('luggage')
        batch_op.drop_column('doors')

    # ### end Alembic commands ###
